### ISSUE TITLE
Opaque hexadecimal color values should be resolved to rgb

### ISSUE THREAD

**Issue by cdoublev** [jsdom/cssstyle#135]
This [test expectation](https://github.com/jsdom/cssstyle/blob/b527ed722364dc6d156487c652df100572075dee/lib/CSSStyleDeclaration.test.js#L197) is wrong:

```js
style.color = '#ffffffff';
expect(style.color).toEqual('rgba(255, 255, 255, 1)');
```

In Chrome/Firefox:

```js
target.style.color = '#ffffffff'
console.log(target.style.color) // "rgb(255, 255, 255)"
```

Though I believe that this is not described in any specification.

**Comment by asamuzaK** [comment]
Ref https://drafts.csswg.org/css-color-4/#css-serialization-of-srgb

> if the alpha is exactly 1, the [rgb()](https://drafts.csswg.org/css-color-4/#funcdef-rgb) form is used, with an implicit alpha; otherwise, the [rgba()](https://drafts.csswg.org/css-color-4/#funcdef-rgba) form is used, with an explicit alpha value.
